### ISSUE TITLE
Model Integrated Nuclio Scheduler Architecture

### ISSUE THREAD

**Issue by KonsumGandalf** [valentin-carl/nuclio#22]
Model the scheduler integrated in the nuclio environment.

Linked issue: https://github.com/valentin-carl/nuclio/issues/20

Created Model
![nuxus-deployment](https://github.com/valentin-carl/nuclio/assets/66205241/e59ef735-656b-4ff7-ac60-be47f1a1cf36)

Modified Model
![nexus-class](https://github.com/valentin-carl/nuclio/assets/66205241/0f80d1a8-fe23-4063-bc61-b3d89c596627)

**Comment by Persists** [comment]
lgtm
